server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://your_host:your_port/your_name_schema"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: your_pass
    username: your_user_name
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "your_key"
  # in second
  # in seconds
